/*

-- Date: 2012-08-17 12:00
*/

DELETE  FROM `champperso`;


INSERT INTO `champperso` (`id`,`pattern`,`libelle`,`dateCreation`,`dateModification`,`beanValue`,`idAgence`) VALUES (129,'@INTER_NOM','INTER nom',NULL,NULL,'nom',1),
 (130,'@INTER_NOMJEUNEFILLE','INTER nomJeuneFille',NULL,NULL,'nomJeuneFille',1),
 (131,'@INTER_PRENOM','INTER prenom',NULL,NULL,'prenom',1),
 (132,'@INTER_NUMEROSALARIE','INTER numeroSalarie',NULL,NULL,'numeroSalarie',1),
 (133,'@INTER_NUMPIECEIDENTITE','INTER numPieceIdentite',NULL,NULL,'numPieceIdentite',1),
 (134,'@INTER_DATENAISSANCE','INTER dateNaissance',NULL,NULL,'dateNaissance',1),
 (135,'@INTER_NATIONALITE','INTER nationalite',NULL,NULL,'nationalite',1),
 (136,'@INTER_COMMENTAIRE','INTER commentaire',NULL,NULL,'commentaire',1),
 (137,'@INTER_ETUDES','INTER etudes',NULL,NULL,'etudes',1),
 (138,'@INTER_COMMENTAIRECOMPETENCES','INTER commentaireCompetences',NULL,NULL,'commentaireCompetences',1),
 (139,'@INTER_DATEENTREE','INTER dateEntree',NULL,NULL,'dateEntree',1),
 (140,'@INTER_DATESORTIE','INTER dateSortie',NULL,NULL,'dateSortie',1),
 (141,'@INTER_DATECT','INTER dateCT',NULL,NULL,'dateCT',1),
 (142,'@INTER_INTITULEPOSTE','INTER intitulePoste',NULL,NULL,'intitulePoste',1),
 (143,'@INTER_DIPLOME','INTER diplome',NULL,NULL,'diplome',1),
 (144,'@INTER_DATEFINCDD','INTER dateFinCdd',NULL,NULL,'dateFinCdd',1),
 (145,'@INTER_LIEUNAISSANCE','INTER lieuNaissance',NULL,NULL,'lieuNaissance',1),
 (146,'@INTER_NUMEROSECU','INTER numeroSecu',NULL,NULL,'numeroSecu',1),
 (147,'@INTER_ADRESSE','INTER adresse',NULL,NULL,'adresse',1),
 (148,'@INTER_CODEPOSTAL','INTER codePostal',NULL,NULL,'codePostal',1),
 (149,'@INTER_VILLE','INTER ville',NULL,NULL,'ville',1),
 (150,'@INTER_TELEPHONE','INTER telephone',NULL,NULL,'telephone',1),
 (151,'@INTER_TELEPHONEMOBILE1','INTER telephoneMobile1',NULL,NULL,'telephoneMobile1',1),
 (152,'@INTER_TELEPHONEMOBILE2','INTER telephoneMobile2',NULL,NULL,'telephoneMobile2',1),
 (153,'@INTER_EMAIL','INTER email',NULL,NULL,'email',1),
 (154,'@INTER_EMAIL2','INTER email2',NULL,NULL,'email2',1),
 (155,'@INTER_CIVILITE','INTER civilite',NULL,NULL,'civilite',1),
 (156,'@INTER_TEMPSTRAVAIL','INTER tempsTravail',NULL,NULL,'tempsTravail',1),
 (157,'@INTER_MODEREGLEMENT','INTER modeReglement',NULL,NULL,'modeReglement',1),
 (158,'@INTER_PRESTATAIRE','INTER prestataire',NULL,NULL,'prestataire',1),
 (159,'@INTER_MANDATAIRE','INTER mandataire',NULL,NULL,'mandataire',1),
 (160,'@INTER_TEMPSPLEIN','INTER tempsPlein',NULL,NULL,'tempsPlein',1),
 (161,'@INTER_RIB','INTER rib',NULL,NULL,'rib',1),
 (162,'@INTER_TITULAIRE','INTER titulaire',NULL,NULL,'titulaire',1),
 (163,'@INTER_CODEBANQUE','INTER codeBanque',NULL,NULL,'codeBanque',1),
 (164,'@INTER_NOMBANQUE','INTER nomBanque',NULL,NULL,'nomBanque',1),
 (165,'@INTER_CODEBIC','INTER codeBic',NULL,NULL,'codeBic',1),
 (166,'@INTER_CODEIBAN','INTER codeIban',NULL,NULL,'codeIban',1),
 (167,'@INTER_CODEGUICHET','INTER codeGuichet',NULL,NULL,'codeGuichet',1),
 (168,'@INTER_NUMEROCOMPTE','INTER numeroCompte',NULL,NULL,'numeroCompte',1),
 (169,'@INTER_CLERIB','INTER cleRib',NULL,NULL,'cleRib',1),
 (170,'@INTER_CONTRATHORAIRE','INTER contratHoraire',NULL,NULL,'contratHoraire',1),
 (171,'@INTER_COEFFICIENT','INTER coefficient',NULL,NULL,'coefficient',1),
 (172,'@INTER_TAUXHORAIRE','INTER tauxHoraire',NULL,NULL,'tauxHoraire',1),
 (173,'@INTER_NUMEROSEJOUR','INTER numeroSejour',NULL,NULL,'numeroSejour',1),
 (174,'@INTER_NUMCARTETRAVAIL','INTER numCarteTravail',NULL,NULL,'numCarteTravail',1),
 (175,'@INTER_DATEVALIDITESEJOUR','INTER dateValiditeSejour',NULL,NULL,'dateValiditeSejour',1),
 (176,'@INTER_DATEVISITEMEDICALE','INTER dateVisiteMedicale',NULL,NULL,'dateVisiteMedicale',1),
 (177,'@INTER_VOLUMEHORAIREMENSUELEFFECTUE','INTER volumeHoraireMensuelEffectue',NULL,NULL,'volumeHoraireMensuelEffectue',1),
 (178,'@INTER_DATECREATION','INTER dateCreation',NULL,NULL,'dateCreation',1),
 (179,'@INTER_TYPECONTRAT','INTER typeContrat',NULL,NULL,'typeContrat',1),
 (180,'@INTER_TYPEAFFICHAGECONTRAT','INTER typeAffichageContrat',NULL,NULL,'typeAffichageContrat',1),
 (181,'@INTER_NBHEURESCONTRAT','INTER nbHeuresContrat',NULL,NULL,'nbHeuresContrat',1),
 (182,'@BENEF_NOM','BENEF nom',NULL,NULL,'nom',1),
 (183,'@BENEF_PRENOM','BENEF prenom',NULL,NULL,'prenom',1),
 (184,'@BENEF_PRESTATAIRE','BENEF prestataire',NULL,NULL,'prestataire',1),
 (185,'@BENEF_MANDATAIRE','BENEF mandataire',NULL,NULL,'mandataire',1),
 (186,'@BENEF_DEPANNAGE','BENEF depannage',NULL,NULL,'depannage',1),
 (188,'@BENEF_MUTUELLE','BENEF mutuelle',NULL,NULL,'mutuelle',1),
 (189,'@BENEF_NUMEROSECU','BENEF numeroSecu',NULL,NULL,'numeroSecu',1),
 (190,'@BENEF_ADRESSE','BENEF adresse',NULL,NULL,'adresse',1),
 (191,'@BENEF_CODEPOSTAL','BENEF codePostal',NULL,NULL,'codePostal',1),
 (192,'@BENEF_VILLE','BENEF ville',NULL,NULL,'ville',1),
 (193,'@BENEF_TELEPHONE','BENEF telephone',NULL,NULL,'telephone',1),
 (194,'@BENEF_TELEPHONEBUREAU','BENEF telephoneBureau',NULL,NULL,'telephoneBureau',1),
 (195,'@BENEF_TELEPHONEMOBILE','BENEF telephoneMobile',NULL,NULL,'telephoneMobile',1),
 (196,'@BENEF_EMAIL','BENEF email',NULL,NULL,'email',1),
 (197,'@BENEF_TXPARTICPATION','BENEF txParticpation',NULL,NULL,'txParticpation',1),
 (198,'@BENEF_ACTIVITE','BENEF activite',NULL,NULL,'activite',1),
 (199,'@BENEF_MENSUALISE','BENEF mensualise',NULL,NULL,'mensualise',1),
 (200,'@BENEF_ABOMENSUELMANDATAIRE','BENEF aboMensuelMandataire',NULL,NULL,'aboMensuelMandataire',1),
 (201,'@BENEF_FRAISDEPLACEMENTMENSUELHT','BENEF fraisDeplacementMensuelHt',NULL,NULL,'fraisDeplacementMensuelHt',1),
 (202,'@BENEF_RIB','BENEF rib',NULL,NULL,'rib',1),
 (203,'@BENEF_TITULAIRE','BENEF titulaire',NULL,NULL,'titulaire',1),
 (204,'@BENEF_CODEBANQUE','BENEF codeBanque',NULL,NULL,'codeBanque',1),
 (205,'@BENEF_NOMBANQUE','BENEF nomBanque',NULL,NULL,'nomBanque',1),
 (206,'@BENEF_CODEBIC','BENEF codeBic',NULL,NULL,'codeBic',1),
 (207,'@BENEF_CODEIBAN','BENEF codeIban',NULL,NULL,'codeIban',1),
 (208,'@BENEF_CODEGUICHET','BENEF codeGuichet',NULL,NULL,'codeGuichet',1),
 (209,'@BENEF_NUMEROCOMPTE','BENEF numeroCompte',NULL,NULL,'numeroCompte',1),
 (210,'@BENEF_CLERIB','BENEF cleRib',NULL,NULL,'cleRib',1),
 (211,'@BENEF_SECTEUR','BENEF secteur',NULL,NULL,'secteur',1),
 (212,'@BENEF_BESOINS','BENEF besoins',NULL,NULL,'besoins',1),
 (213,'@BENEF_COMMENTAIRES','BENEF commentaires',NULL,NULL,'commentaires',1),
 (214,'@BENEF_CODECLIENT','BENEF codeClient',NULL,NULL,'codeClient',1),
 (215,'@BENEF_MODEREGLEMENT','BENEF modeReglement',NULL,NULL,'modeReglement',1),
 (216,'@BENEF_ACOMPTE','BENEF acompte',NULL,NULL,'acompte',1),
 (217,'@BENEF_DATEFINBESOIN','BENEF dateFinBesoin',NULL,NULL,'dateFinBesoin',1),
 (218,'@BENEF_DATESUPPRESSIONLOGIQUE','BENEF dateSuppressionLogique',NULL,NULL,'dateSuppressionLogique',1),
 (219,'@BENEF_SITUATION','BENEF situation',NULL,NULL,'situation',1),
 (220,'@BENEF_FORFAITMENSUEL','BENEF forfaitMensuel',NULL,NULL,'forfaitMensuel',1),
 (221,'@BENEF_NUMEROCAF','BENEF numeroCaf',NULL,NULL,'numeroCaf',1),
 (222,'@BENEF_NUMEROURSAFF','BENEF numeroUrsaff',NULL,NULL,'numeroUrsaff',1),
 (223,'@BENEF_FORFAITMENSUELTTC','BENEF forfaitMensuelTtc',NULL,NULL,'forfaitMensuelTtc',1),
 (224,'@BENEF_DATEINTERVENTION','INTER BENEF dateIntervention',NULL,NULL,'dateIntervention',1),
 (225,'@BENEF_CIVILITE','BENEF civilite',NULL,NULL,'civilite',1),
 (226,'@BENEF_COMMENTAIRE','BENEF commentaire',NULL,NULL,'commentaire',1),
 (227,'@AG_LIBCODEAGENCE','AGENCE libCodeAgence',NULL,NULL,'libCodeAgence',1),
 (228,'@AG_NOMSOCIETE','AGENCE nomSociete',NULL,NULL,'nomSociete',1),
 (229,'@AG_ADRESSE','AGENCE adresse',NULL,NULL,'adresse',1),
 (230,'@AG_CODEPOSTAL','AGENCE codePostal',NULL,NULL,'codePostal',1),
 (231,'@AG_VILLE','AGENCE ville',NULL,NULL,'ville',1),
 (232,'@AG_NUMEROAGREMENT','AGENCE numeroAgrement',NULL,NULL,'numeroAgrement',1),
 (233,'@AG_ALIASMAIL','AGENCE aliasMail',NULL,NULL,'aliasMail',1),
 (234,'@AG_CONTENUMAILFACTURE','AGENCE contenuMailFacture',NULL,NULL,'contenuMailFacture',1),
 (235,'@AG_CONTENUMAILRELANCEFACTURE','AGENCE contenuMailRelanceFacture',NULL,NULL,'contenuMailRelanceFacture',1),
 (236,'@AG_NBJOURSECHEANCEFACTURE','AGENCE nbJoursEcheanceFacture',NULL,NULL,'nbJoursEcheanceFacture',1),
 (237,'@AG_AFFICHERNUMEROSECU','AGENCE afficherNumeroSecu',NULL,NULL,'afficherNumeroSecu',1),
 (238,'@AG_CATEGORIE','AGENCE categorie',NULL,NULL,'categorie',1),
 (239,'@AG_NOMBANQUE','AGENCE nomBanque',NULL,NULL,'nomBanque',1),
 (240,'@AG_CODEBANQUE','AGENCE codeBanque',NULL,NULL,'codeBanque',1),
 (241,'@AG_CODEGUICHET','AGENCE codeGuichet',NULL,NULL,'codeGuichet',1),
 (242,'@AG_NUMEROCOMPTE','AGENCE numeroCompte',NULL,NULL,'numeroCompte',1),
 (243,'@AG_CLERIB','AGENCE cleRib',NULL,NULL,'cleRib',1),
 (244,'@AG_TELEPHONE','AGENCE telephone',NULL,NULL,'telephone',1),
 (245,'@AG_FAX','AGENCE fax',NULL,NULL,'fax',1),
 (246,'@AG_RCS','AGENCE rcs',NULL,NULL,'rcs',1),
 (247,'@AG_NAF','AGENCE naf',NULL,NULL,'naf',1),
 (248,'@AG_EMAIL','AGENCE email',NULL,NULL,'email',1),
 (249,'@AG_SITE','AGENCE site',NULL,NULL,'site',1),
 (250,'@AG_LOGO','AGENCE logo',NULL,NULL,'logo',1),
 (251,'@AG_SIRET','AGENCE siret',NULL,NULL,'siret',1),
 (252,'@AG_NOMGERANT','AGENCE nomGerant',NULL,NULL,'nomGerant',1),
 (253,'@AG_CAPITAL','AGENCE capital',NULL,NULL,'capital',1),
 (254,'@AG_TVAINTRA','AGENCE tvaIntra',NULL,NULL,'tvaIntra',1),
 (255,'@AG_URSSAF','AGENCE urssaf',NULL,NULL,'urssaf',1),
 (256,'@AG_TYPEORGANISME','AGENCE typeOrganisme',NULL,NULL,'typeOrganisme',1),
 (257,'@PROS_NOM','Prospect nom',NULL,NULL,'nom',1),
 (258,'@PROS_PRENOM','Prospect prenom',NULL,NULL,'prenom',1),
 (259,'@PROS_MANDATAIRE','Prospect mandataire',NULL,NULL,'mandataire',1),
 (260,'@PROS_DEMANDEREGULIERE','Prospect demandeReguliere',NULL,NULL,'demandeReguliere',1),
 (261,'@PROS_EXIGENCES','Prospect exigences',NULL,NULL,'exigences',1),
 (262,'@PROS_MODEREGLEMENT','Prospect modeReglement',NULL,NULL,'modeReglement',1),
 (263,'@PROS_ZONESCOLAIRE','Prospect zoneScolaire',NULL,NULL,'zoneScolaire',1),
 (264,'@PROS_DEPOTGARANTIE','Prospect depotGarantie',NULL,NULL,'depotGarantie',1),
 (265,'@PROS_BESOINVEHICULE','Prospect besoinVehicule',NULL,NULL,'besoinVehicule',1),
 (266,'@PROS_CONNAISSANCEJS','Prospect connaissanceJS',NULL,NULL,'connaissanceJS',1),
 (267,'@PROS_ADRESSE','Prospect adresse',NULL,NULL,'adresse',1),
 (268,'@PROS_CODEPOSTAL','Prospect codePostal',NULL,NULL,'codePostal',1),
 (269,'@PROS_VILLE','Prospect ville',NULL,NULL,'ville',1),
 (270,'@PROS_TELEPHONE','Prospect telephone',NULL,NULL,'telephone',1),
 (271,'@PROS_TELEPHONEMOBILE1','Prospect telephoneMobile1',NULL,NULL,'telephoneMobile1',1),
 (272,'@PROS_EMAIL','Prospect email',NULL,NULL,'email',1),
 (273,'@PROS_EMAIL2','Prospect email2',NULL,NULL,'email2',1),
 (274,'@PROS_CIVILITE','Prospect civilite',NULL,NULL,'civilite',1),
 (275,'@PROS_COMMENTAIRE','Prospect commentaire',NULL,NULL,'commentaire',1),
 (276,'@PROS_RAISONNONVALIDATION','Prospect raisonNonValidation',NULL,NULL,'raisonNonValidation',1),
 (277,'@PROS_AGENCE','Prospect agence',NULL,NULL,'agence',1),
 (278,'@PROS_LISTEENFANTS','Prospect listeEnfants',NULL,NULL,'listeEnfants',1),
 (279,'@PROS_LISTEPRESTATIONS','Prospect listePrestations',NULL,NULL,'listePrestations',1),
 (280,'@PROS_LISTETAUX','Prospect listeTaux',NULL,NULL,'listeTaux',1),
 (281,'@PROS_DATEDEMANDEREPONSE','Prospect dateDemandeReponse',NULL,NULL,'dateDemandeReponse',1),
 (282,'@PROS_DATERDV','Prospect dateRdv',NULL,NULL,'dateRdv',1),
 (283,'@DVS_MENSUALITEFIXEEMANUELLEMENT','Devis mensualiteFixeeManuellement',NULL,NULL,'mensualiteFixeeManuellement',1),
 (284,'@DVS_PERIODICITESEMAINE','Devis periodiciteSemaine',NULL,NULL,'periodiciteSemaine',1),
 (285,'@DVS_MONTANTPAJE','Devis montantPaje',NULL,NULL,'montantPaje',1),
 (286,'@DVS_NBSEMAINES','Devis nbSemaines',NULL,NULL,'nbSemaines',1),
 (287,'@DVS_NBHEURESMENSUELLESVARIABLE','Devis nbHeuresMensuellesVariable',NULL,NULL,'nbHeuresMensuellesVariable',1),
 (288,'@DVS_TYPEPRESTATIONPLANNINGVARIABLE','Devis typePrestationPlanningVariable',NULL,NULL,'typePrestationPlanningVariable',1),
 (289,'@DVS_TAUXTTCPRESTATIONVARIABLE','Devis tauxTtcPrestationVariable',NULL,NULL,'tauxTtcPrestationVariable',1),
 (290,'@DVS_NBMENS','Devis nbMensualites',NULL,NULL,'nbMensualites',1),
 (291,'@DVS_NBENFANTSAGARDER','Devis nbEnfantsAGarder',NULL,NULL,'nbEnfantsAGarder',1),
 (292,'@DVS_NBKILOMETRESHEBDO','Devis nbKilometresHebdo',NULL,NULL,'nbKilometresHebdo',1),
 (293,'@DVS_COMMENTAIRES','Devis commentaires',NULL,NULL,'commentaires',1),
 (294,'@DVS_DEPOTGARANTIE','Devis depotGarantie',NULL,NULL,'depotGarantie',1),
 (295,'@DVS_FRAISADHESIONLIBRE','Devis fraisAdhesionLibre',NULL,NULL,'fraisAdhesionLibre',1),
 (296,'@DVS_STATUTDEVIS','Devis statutDevis',NULL,NULL,'statutDevis',1),
 (297,'@DVS_MOTIFREFUS','Devis motifRefus',NULL,NULL,'motifRefus',1),
 (298,'@DVS_DATECREATION','Devis dateCreation',NULL,NULL,'dateCreation',1),
 (299,'@DVS_DATEMAJ','Devis dateMaj',NULL,NULL,'dateMaj',1),
 (300,'@DVS_DATEADHESION','Devis dateAdhesion',NULL,NULL,'dateAdhesion',1),
 (301,'@DVS_MONTANTLISSE','Devis montantLisse',NULL,NULL,'montantLisse',1),
 (302,'@DVS_DATEDEBUT','Devis dateDebut',NULL,NULL,'dateDebut',1),
 (303,'@DVS_DATEFIN','Devis dateFin',NULL,NULL,'dateFin',1),
 (304,'@DVS_VACANCESSCOLAIRES','Devis vacancesScolaires',NULL,NULL,'vacancesScolaires',1),
 (305,'@DVS_NBMINUTESHEBDO','Devis nbMinutesHebdo',NULL,NULL,'nbMinutesHebdo',1),
 (306,'@DVS_NBMINUTESPERIODE','Devis nbMinutesPeriode',NULL,NULL,'nbMinutesPeriodePretty',1),
 (307,'@DVS_NBMINMENS','Devis nbMinutesMensuel',NULL,NULL,'nbMinutesMensuelPretty',1),
 (308,'@DVS_TXHORREDUCIMPOT','Devis tauxHoraireApresReductionImpot',NULL,NULL,'tauxHoraireApresReductionImpot',1),
 (309,'@DVS_MONTANTHEBDO','Devis montantHebdo',NULL,NULL,'montantHebdo',1),
 (310,'@DVS_MONTANTMENSUELVARIABLE','Devis montantMensuelVariable',NULL,NULL,'montantMensuelVariable',1),
 (311,'@DVS_MONTANTPERIODE','Devis montantPeriode',NULL,NULL,'montantPeriode',1),
 (312,'@DVS_MONTANTFRAISKMHEBDO','Devis montantFraisKmHebdo',NULL,NULL,'montantFraisKmHebdo',1),
 (313,'@DVS_MONTANTFRAISKMMENSUEL','Devis montantFraisKmMensuel',NULL,NULL,'montantFraisKmMensuel',1),
 (314,'@DVS_MONTANTFRAISKMPERIODE','Devis montantFraisKmPeriode',NULL,NULL,'montantFraisKmPeriode',1),
 (315,'@DVS_SOUSTOTALHEBDO','Devis sousTotalHebdo',NULL,NULL,'sousTotalHebdo',1),
 (316,'@DVS_SOUSTOTALMENSUEL','Devis sousTotalMensuel',NULL,NULL,'sousTotalMensuel',1),
 (317,'@DVS_SOUSTOTALPERIODE','Devis sousTotalPeriode',NULL,NULL,'sousTotalPeriode',1),
 (318,'@DVS_NBMOISMENSUALITE','Devis nbMoisMensualite',NULL,NULL,'nbMoisMensualite',1),
 (319,'@DVS_MTMENS','Devis montantMensualite',NULL,NULL,'montantMensualite',1),
 (320,'@DVS_MONTANTCOTISATION','Devis montantCotisation',NULL,NULL,'montantCotisation',1),
 (321,'@DVS_MONTANTPLAFONDPAJE','Devis montantPlafondPaje',NULL,NULL,'montantPlafondPaje',1),
 (322,'@DVS_MTPAJEENCOMPTE','Devis montantPajePrisEnCompte',NULL,NULL,'montantPajePrisEnCompte',1),
 (323,'@DVS_MTACHARGE','Devis montantRestantACharge',NULL,NULL,'montantRestantACharge',1),
 (324,'@DVS_CTMENSREDUCIMPOT','Devis coutMensuelApresReductionImpot',NULL,NULL,'coutMensuelApresReductionImpot',1),
 (325,'@DVS_CTANREDUCIMPOT','Devis coutAnnuelApresReductionImpot',NULL,NULL,'coutAnnuelApresReductionImpot',1),
 (326,'@DVS_VOLUMEHORAIREHEBDOMADAIRE','Devis volumeHoraireHebdomadaire',NULL,NULL,'volumeHoraireHebdomadaire',1),
 (327,'@DVS_VOLUMEHORAIREMENSUEL','Devis volumeHoraireMensuel',NULL,NULL,'volumeHoraireMensuel',1),
 (328,'@DVS_VOLUMEHORAIRETOTAL','Devis volumeHoraireTotal',NULL,NULL,'volumeHoraireTotal',1),
 (329,'@DVS_PRESTAOBJ','Devis prestaObj',NULL,NULL,'prestaObj',1),
 (330,'@DVS_CYCLE','Devis cycle',NULL,NULL,'cycle',1),
 (331,'@DVS_PRESTACYCLE','Devis prestaCycle',NULL,NULL,'prestaCycle',1),
 (332,'@DVS_TAUXPRESTACYCLE','Devis tauxPrestaCycle',NULL,NULL,'tauxPrestaCycle',1),
 (333,'@DVS_AUTEUR','Devis auteur',NULL,NULL,'auteur',1),
 (334,'@DVS_PLANNINGVARIABLE','Devis planningVariable',NULL,NULL,'planningVariable',1),
 (335,'@DVS_COMMENTAIRESPLANNINGVARIABLE','Devis commentairesPlanningVariable',NULL,NULL,'commentairesPlanningVariable',1),
 (336,'@DVS_NUMDEVIS','DEVIS NUMDEVIS',NULL,NULL,'numDevis',1),
 (337,'@AG_TARIFKM','Agence prix km',NULL,NULL,'tarifKmDevis',1),
 (338,'@DVS_MTPAJEPERIODE','Devis MTPAJEPERIODE',NULL,NULL,'montantPajePrisEnComptePeriode',1),
 (339,'@DVS_DATE','Date edition',NULL,NULL,'dateEdition',1),
 (340,'@DVS_BESOIN','devis besoin',NULL,NULL,'besoin',1),
 (341,'@AG_AGREDATE','Ag date agrement',NULL,NULL,'agrementDate',1),
 (361,'@AG_LBCOURT','Agence lb court',NULL,NULL,'utiliserLibelleCourtPourDevis',1),
 (401,'@AG_AGRESIMPLE','Ag agre simple',NULL,NULL,'numeroAgrementSimple',1),
 (411,'@AG_FONCTION','Ag fonction',NULL,NULL,'fonction',1),
 (421,'@DVS_NBMINTOTSEM','Prospect nb min total semaine',NULL,NULL,'nbMinutesHebdoTotalPretty',1),
 (431,'@AG_FORME','Ag forme juridique',NULL,NULL,'formeJuridique',1),
 (441,'@DVS_NBMINTOTSEM','Prospect nb min total semaine',NULL,NULL,'nbMinutesHebdoTotalPretty',1),
 (451,'@DVS_CTPERIODEREDUCIMPOT','DVS reduc periode fiscale',NULL,NULL,'deductionFiscalePeriode',1),
 (461,'@DVS_MTACHARGEPERIODE','Devis montantRestantACharge periode',NULL,NULL,'montantRestantAChargePeriode',1),
 (471,'@AG_DTREG','Agence date reglement',NULL,NULL,'dateReglementFacture',1),
 (481,'@AG_FRAISGESTION','agence frais gestion',NULL,NULL,'fraisGestion',1),
 (491,'@AG_DELAI','agence delai remplacement',NULL,NULL,'delaiRemplacementDevis',1),
 (501,'@AG_TXREAL','agence tx realisation',NULL,NULL,'tauxRealisationDevis',1),
 (511,'@AG_ECART','agence ecart volume',NULL,NULL,'ecartVolumeDevis',1),
 (521,'@DVS_DEPOT','devis depot garantie',NULL,NULL,'depotGarantie',1),
 (531,'@DVS_NBMINMENSVAR','devis nb mens',NULL,NULL,'nbHeuresMensuellesTotalVariable',1),
 (541,'@DVS_LIBTVA','devis lib tva',NULL,NULL,'libelleTva',1),
 (545,'@AG_RESEAUFRAN','agence reseau de franchise',NULL,NULL,'reseauFranchise',1),
 (546,'@AG_ADRESSEVISITE','agence adresse de la visite medicale',NULL,NULL,'adresseVisiteMedical',1),
 (547,'@AG_RCSVILLE','agence rcs ville',NULL,NULL,'rcsVille',1),
 (548,'@INTER_SALAIREBRUT','inter salaireBrutMensuel',NULL,NULL,'salaireBrutMensuel',1),
 (549,'@FACT_DATE','FACT date' ,NULL,NULL,'dateEdition',1),
 (550,'@FACT_TOTALHEURE','FACT totalHeuresFact',NULL,NULL,'totalHeuresFact',1),
 (551,'@FACT_TOTALTTC','FACT totalTTC',NULL,NULL,'totalTTC',1),
 (600,'@INTER_AGE','INTER age',NULL,NULL,'age',1),
 (601,'@INTER_NBENFANT','INTER nb enfants',NULL,NULL,'nbEnfantsACharge',1),
 (602,'@INTER_DATEPERMIS','INTER datePermis',NULL,NULL,'datePermis',1),
 (603,'@INTER_DATEPOLEEMPLOI','INTER dateInscriptionPoleEmpl',NULL,NULL,'dateInscriptionPoleEmpl',1),
 (604,'@INTER_IDPOLEEMPLOI','INTER idPoleEmploi',NULL,NULL,'idPoleEmploi',1),
 (605,'@INTER_IDCAF','INTER idCaf',NULL,NULL,'idCaf',1),
 (606,'@INTER_PRESCRIPTION','INTER datePremierePrescription',NULL,NULL,'datePremierePrescription',1),
 (607,'@INTER_COMMENTAIREPARCOURS','INTER commentaireParcours',NULL,NULL,'commentaireParcours',1),
 (611,'@STR_NOM','STR nomStructure',NULL,NULL,'nomStructure',1),
 (612,'@STR_NOMRESP','STR nomResponsable',NULL,NULL,'nomResponsable',1),
 (613,'@STR_PRENOMRESP','STR  prenomResponsable',NULL,NULL,'prenomResponsable',1),
 (614,'@STR_CIVILITERESP','STR  civiliteResponsable',NULL,NULL,'civiliteResponsable',1),
 (615,'@STR_FONCTIONRESP','STR fonctionResponsable',NULL,NULL,'fonctionResponsable',1),
 (616,'@STR_ADRESSE','STR adresse',NULL,NULL,'adresse',1),
 (617,'@STR_CODEPOSTAL','STR codePostal',NULL,NULL,'codePostal',1),
 (618,'@STR_VILLE','STR ville',NULL,NULL,'ville',1),
 (619,'@STR_EMAIL','STR email ',NULL,NULL,'email',1),
 (620,'@STR_SITE','STR siteWeb',NULL,NULL,'siteWeb',1),
 (621,'@STR_TYPESTR','STR typeStructure',NULL,NULL,'typeStructure',1),
 (623,'@STR_BUREAU','STR telephoneBureau',NULL,NULL,'telephoneBureau',1),
 (624,'@STR_MOBILE','STR telephoneMobile',NULL,NULL,'telephoneMobile',1),
 (627,'@STR_SIRET','STR numeroSiret',NULL,NULL,'numeroSiret',1),
 (628,'@STR_NBBENEF','STR nbBeneficiaires',NULL,NULL,'nbBeneficiaires',1),
 (629,'@STR_NBHEURES','STR nbHeures',NULL,NULL,'nbHeures',1),
 (630,'@STR_EFFECTIF','STR effectif',NULL,NULL,'effectif',1),
 (631,'@STR_EFFECTIFMANDA','STR effectifMandataire',NULL,NULL,'effectifMandataire',1),
 (632,'@STR_NBETP','STR nbETP',NULL,NULL,'nbETP',1),
 (633,'@STR_TRANCHESALARIE','STR trancheSalarie',NULL,NULL,'trancheSalarie',1),
 (634,'@STR_FEDERATION','STR federation',NULL,NULL,'federation',1),
 (635,'@STR_ORGANISME','STR organismeFormateur',NULL,NULL,'organismeFormateur',1),
 (636,'@STR_CONVENTIONCOL','STR conventionCollective',NULL,NULL,'conventionCollective',1),
 (637,'@STR_ADHERENT','STR adherentAmadom',NULL,NULL,'adherentAmadom',1),
 (638,'@STR_DATEADHESION','STR dateAdhesion',NULL,NULL,'dateAdhesion',1),
 (639,'@STR_COTISATION','STR tauxCotisation',NULL,NULL,'tauxCotisation',1),
 (640,'@STR_FACTURE','STR tauxFacture',NULL,NULL,'tauxFacture',1),
 (641,'@STR_AGREMENT','STR agrement',NULL,NULL,'agrement',1),
 (642,'@STR_DATEAGREMENT','STR dateAgrement',NULL,NULL,'dateAgrement',1),
 (643,'@STR_NUMAGREMENT','STR numeroAgrement',NULL,NULL,'numeroAgrement',1),
 (644,'@STR_DATERENOUV','STR dateRenouvellement',NULL,NULL,'dateRenouvellement',1),
 (645,'@STR_CERTIF','STR certification',NULL,NULL,'certification',1),
 (646,'@STR_DATECERTIF','STR dateCertification',NULL,NULL,'dateCertification',1),
 (647,'@STR_NUMCERTIF','STR numeroCertification',NULL,NULL,'numeroCertification',1),
 (648,'@INTER_METIERCIBLE','INTER metierCible',NULL,NULL,'metierCible',1),
 (649,'@INTER_METIERCIBLESEC','INTER metierCibleSecondaire',NULL,NULL,'metierCibleSecondaire',1);